image: docker:stable

services:
  - docker:stable-dind

before_script:
  - docker info

cache:
  paths:
    - node_modules

build:
  stage: build
  tags:
    - common
  script:
    - docker build -f client/Dockerfile -t client client
