cache:
  paths:
    - client/node_modules
    - server/node_modules

deploy:
  stage: deploy
  tags:
    - common
  script:
    - docker-compose -f docker-compose.yml -f production.yml build
    - docker-compose -f docker-compose.yml -f production.yml down
    - docker-compose -f docker-compose.yml -f production.yml up -d --force-recreate
