services:
  client:
    build:
      context: ./client
      args:
        - VUE_APP_SERVER=ws://localhost:3000
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:80
  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - ORIGIN=http://localhost:8080
