services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:80
  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
