services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:80
    environment:
      - VUE_APP_SERVER=ws://localhost:3000
  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - ORIGIN=http://localhost:8080
